package intake

const (
	Energy            Kind = "energy.energy"
	Fat               Kind = "nutrient.fat"
	Saturated         Kind = "nutrient.saturated"
	TransFat          Kind = "nutrient.transfat"
	Cholesterol       Kind = "nutrient.cholesterol"
	Sodium            Kind = "nutrient.sodium"
	Carb              Kind = "nutrient.carb"
	Fiber             Kind = "nutrient.dietaryfiber"
	Sugar             Kind = "nutrient.sugar"
	AddedSugar        Kind = "nutrient.addedsugar"
	Protein           Kind = "nutrient.protein"
	VitaminD          Kind = "vitamin.d"
	Calcium           Kind = "mineral.calcium"
	Iron              Kind = "mineral.iron"
	Potassium         Kind = "mineral.potassium"
	Monounsaturated   Kind = "nutrient.monounsaturated"
	Polyunsaturated   Kind = "nutrient.polyunsaturated"
	Water             Kind = "nutrient.water"
	Alcohol           Kind = "nutrient.alcohol"
	Salt              Kind = "nutrient.salt"
	VitaminA          Kind = "vitamin.a"
	VitaminB1         Kind = "vitamin.b1"
	VitaminB2         Kind = "vitamin.b2"
	VitaminB3         Kind = "vitamin.b3"
	VitaminB5         Kind = "vitamin.b5"
	VitaminB6         Kind = "vitamin.b6"
	VitaminB7         Kind = "vitamin.b7"
	VitaminB11        Kind = "vitamin.b11"
	VitaminB12        Kind = "vitamin.b12"
	VitaminC          Kind = "vitamin.c"
	VitaminE          Kind = "vitamin.e"
	VitaminK          Kind = "vitamin.k"
	MineralArsenic    Kind = "mineral.arsenic"
	MineralBoron      Kind = "mineral.boron"
	MineralBiotin     Kind = "mineral.biotin"
	MineralCholine    Kind = "mineral.choline"
	MineralChlorine   Kind = "mineral.chlorine"
	MineralChrome     Kind = "mineral.chrome"
	MineralCobalt     Kind = "mineral.cobalt"
	MineralCopper     Kind = "mineral.copper"
	MineralFluoride   Kind = "mineral.fluoride"
	MineralIodine     Kind = "mineral.iodine"
	MineralFluorine   Kind = "mineral.fluorine"
	MineralManganese  Kind = "mineral.manganese"
	MineralMagnesium  Kind = "mineral.magnesium"
	MineralMolybdenum Kind = "mineral.molybdenum"
	MineralPhosphorus Kind = "mineral.phosphorus"
	MineralSelenium   Kind = "mineral.selenium"
	MineralRubidium   Kind = "mineral.rubidium"
	MineralSilicon    Kind = "mineral.silicon"
	MineralTin        Kind = "mineral.tin"
	MineralSulfur     Kind = "mineral.sulfur"
	MineralZinc       Kind = "mineral.zinc"
	MineralVanadium   Kind = "mineral.vanadium"
)

type Kind string

func (k Kind) String() string {
	return string(k)
}
