name: Run Go tests

on:
  push:
    branches: [main]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - 
        name: Verify before build
        run: |
          go mod tidy
          go vet ./...
      - 
        name: Test (and generate coverage)
        run: |
          go test \
            -coverpkg=./... \
            -covermode=atomic \
            -coverprofile=coverage.txt ./...
      - 
        if: success()
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
